=== opentdf/tests/frontend/containers/kas/kas_core/tdf3_kas_core/schema/tdf3_policy_sync_schema.json
{
  "$id": "http://virtru.com/tdf3_policy_sync.json",
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "binding": { "$ref": "#/definitions/binding" },
    "entity": { "$ref": "#/definitions/entity" },
    "policy": { "$ref": "#/definitions/policy" },
    "wrapped_key": { "$ref": "#/definitions/wrapped_key" },
    "auth_token": { "$ref": "#/definitions/auth_token" },
    "metadata": { "$ref": "#/definitions/metadata" }
  },
  "required": ["binding", "entity", "policy", "wrapped_key", "auth_token"],
  "maxProperties": 6,
  "definitions": {
    "algorithm": {
      "$id": "/properties/algorithm",
      "type": "string",
      "title": "The alrogithm used to encrypt the ciphertext ",
      "default": "",
      "examples": ["AES-256-GCM"]
    },
    "attribute": {
      "type": "string",
      "title": "The Attribute Schema ",
      "default": "",
      "examples": ["PRX", "AAA", "TS", "USA"]
    },
    "attributes": {
      "type": "array",
      "items": { "$ref": "#/definitions/attribute" }
    },
    "auth_token": {
      "$id": "/properties/auth_token",
      "type": "string",
      "title": "Auth token JWT",
      "default": "",
      "examples": [
        "RwpluIcdmSxzdHqPEhDd3jjBbSF8bBpK9CxC+piCTCwdqpTJHDkj40ENHs7oZ4xRL5X5GZAaZaOBdwEMROImSSuOKtwHZWX42TOSdIUpMMK0MXmU85K/G3FMJ7CVmRATUXH5XbES2xm46W3eYiVExkDzRRb+QONI0sYd7ipCwKmoCmzBrGhY83K1fzWz/BAqwGvn7tQMZBIIoef8Q7xaM68tL45MFK5MMvqIAJqiVgIMt98IB2QegQSQHBpFnXfVaEdM37ZeBxDyG9NDSXLGYiXF5J5Af1IhC1ZCWn79sWi4p+hZMRp6qjCR32R3Q+/Jb6ktKVT3kTd4dLRU8+nCEA=="
      ]
    },
    "binding": {
      "type": "string",
      "title": "The Binding Schema ",
      "default": "",
      "examples": ["0Qb8Cpp8qrFZLARRz4XynTa2jFRsEuLU+cKbnRpco2o="]
    },
    "ciphertext": {
      "$id": "/properties/ciphertext",
      "type": "string",
      "title": "The encrypted object",
      "default": "",
      "examples": [
        "RwpluIcdmSxzdHqPEhDd3jjBbSF8bBpK9CxC+piCTCwdqpTJHDkj40ENHs7oZ4xRL5X5GZAaZaOBdwEMROImSSuOKtwHZWX42TOSdIUpMMK0MXmU85K/G3FMJ7CVmRATUXH5XbES2xm46W3eYiVExkDzRRb+QONI0sYd7ipCwKmoCmzBrGhY83K1fzWz/BAqwGvn7tQMZBIIoef8Q7xaM68tL45MFK5MMvqIAJqiVgIMt98IB2QegQSQHBpFnXfVaEdM37ZeBxDyG9NDSXLGYiXF5J5Af1IhC1ZCWn79sWi4p+hZMRp6qjCR32R3Q+/Jb6ktKVT3kTd4dLRU8+nCEA=="
      ]
    },
    "entity": {
      "type": "object",
      "title": "The Entity Schema ",
      "properties": {
        "userId": { "$ref": "#/definitions/userId" },
        "attributes": { "$ref": "#/definitions/attributes" },
        "cert": { "$ref": "#/definitions/cert" },
        "publicKey": { "$ref": "#/definitions/publicKey" },
        "aliases": { "$ref": "#/definitions/aliases" }
      },
      "required": ["attributes", "publicKey", "cert", "userId"],
      "maxProperties": 5
    },
    "aliases": {
      "type": "array",
      "title": "Array of userIds ",
      "default": [],
      "items": { "$ref": "#/definitions/userId" }
    },
    "userId": {
      "type": "string",
      "title": "The entity userId ",
      "default": "",
      "examples": ["a@virtru.com"]
    },
    "cert": {
      "type": "string",
      "title": "The entity cert ",
      "default": "",
      "examples": [
        "RwpluIcdmSxzdHqPEhDd3jjBbSF8bBpK9CxC+piCTCwdqpTJHDkj40ENHs7oZ4xRL5X5GZAaZaOBdwEMROImSSuOKtwHZWX42TOSdIUpMMK0MXmU85K/G3FMJ7CVmRATUXH5XbES2xm46W3eYiVExkDzRRb+QONI0sYd7ipCwKmoCmzBrGhY83K1fzWz/BAqwGvn7tQMZBIIoef8Q7xaM68tL45MFK5MMvqIAJqiVgIMt98IB2QegQSQHBpFnXfVaEdM37ZeBxDyG9NDSXLGYiXF5J5Af1IhC1ZCWn79sWi4p+hZMRp6qjCR32R3Q+/Jb6ktKVT3kTd4dLRU8+nCEA=="
      ]
    },
    "attributes": {
      "type": "array",
      "title": "The EntityAttributes Schema ",
      "default": [],
      "items": { "$ref": "#/definitions/entity_attribute" }
    },
    "entity_attribute": {
      "type": "object",
      "title": "The EntityAttribute Schema ",
      "properties": {
        "jwt": { "$ref": "#/definitions/jwt" }
      },
      "required": ["jwt"],
      "maxProperties": 1
    },
    "iv": {
      "$id": "/properties/iv",
      "type": "string",
      "title": "The initial vector used to encrypt the ciphertext ",
      "default": "",
      "examples": [
        "RwpluIcdmSxzdHqPEhDd3jjBbSF8bBpK9CxC+piCTCwdqpTJHDkj40ENHs7oZ4xRL5X5GZAaZaOBdwEMROImSSuOKtwHZWX42TOSdIUpMMK0MXmU85K/G3FMJ7CVmRATUXH5XbES2xm46W3eYiVExkDzRRb+QONI0sYd7ipCwKmoCmzBrGhY83K1fzWz/BAqwGvn7tQMZBIIoef8Q7xaM68tL45MFK5MMvqIAJqiVgIMt98IB2QegQSQHBpFnXfVaEdM37ZeBxDyG9NDSXLGYiXF5J5Af1IhC1ZCWn79sWi4p+hZMRp6qjCR32R3Q+/Jb6ktKVT3kTd4dLRU8+nCEA=="
      ]
    },
    "metadata": {
      "type": "object",
      "title": "Metadata encrypted with keysplit",
      "properties": {
        "algorithm": { "$ref": "#/definitions/algorithm" },
        "iv": { "$ref": "#/definitions/iv" },
        "ciphertext": { "$ref": "#/definitions/ciphertext" }
      },
      "required": ["algorithm", "iv", "ciphertext"],
      "maxProperties": 4
    },
    "policy": {
      "$id": "/properties/policy",
      "type": "string",
      "title": "The Policy Schema ",
      "default": "",
      "examples": [
        "eyJib2R5IjogeyJkYXRhQXR0cmlidXRlcyI6IFt7InVybCI6ICJodHRwczovL2V4YW1wbGUuY29tL2F0dHIvQ2xhc3NpZmljYXRpb24uUyIsICJuYW1lIjogIlRvcCBTZWNyZXQifSwgeyJ1cmwiOiAiaHR0cHM6Ly9leGFtcGxlLmNvbS9hdHRyL0NPSS5QUlgiLCAibmFtZSI6ICJQcm9qZWN0IFgifV19fQ=="
      ]
    },
    "publicKey": {
      "type": "string",
      "title": "The Public_key Schema ",
      "default": "",
      "examples": [
        "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzNH7sQbY8NyoghL0WWhK\n/YmY0yrYJDm3MCSlRVBKHpB1Zbjes2/SXGKhTCifTtHVF5YABPM+XBVTvpo3paEk\n3vsWYXizFfS5FKtHu3k0CExBMjkD7Wb3Uck2FTTRJlgyonwe6Wd6MzuqDqGWk7Iz\nhxnub6dx+UCCi5ZfXpPL6dFMd936Vu+VrKitYJ7sWVN1jOiMfsh2KvVlG5ycb98q\nwPsbi8U9yek8RtZ9KSsde4Uz+MQx1pFNNFmTJ3Wd4inrZcMqJ5NTaxXHGTAWt88b\nP1r30n93qH5EYlwCrgAkjZkEwF04n6kKDI7rus7VN9rx+SE2dTun+Yw1VwzZTY7P\nrQIDAQAB\n-----END PUBLIC KEY-----\n"
      ]
    },
    "jwt": {
      "type": "string",
      "title": "The JWT token for an attribute",
      "examples": [
        "RwpluIcdmSxzdHqPEhDd3jjBbSF8bBpK9CxC+piCTCwdqpTJHDkj40ENHs7oZ4xRL5X5GZAaZaOBdwEMROImSSuOKtwHZWX42TOSdIUpMMK0MXmU85K/G3FMJ7CVmRATUXH5XbES2xm46W3eYiVExkDzRRb+QONI0sYd7ipCwKmoCmzBrGhY83K1fzWz/BAqwGvn7tQMZBIIoef8Q7xaM68tL45MFK5MMvqIAJqiVgIMt98IB2QegQSQHBpFnXfVaEdM37ZeBxDyG9NDSXLGYiXF5J5Af1IhC1ZCWn79sWi4p+hZMRp6qjCR32R3Q+/Jb6ktKVT3kTd4dLRU8+nCEA=="
      ]
    },
    "wrapped_key": {
      "$id": "/properties/wrapped_key",
      "type": "string",
      "title": "The Wrapped_key Schema ",
      "default": "",
      "examples": [
        "RwpluIcdmSxzdHqPEhDd3jjBbSF8bBpK9CxC+piCTCwdqpTJHDkj40ENHs7oZ4xRL5X5GZAaZaOBdwEMROImSSuOKtwHZWX42TOSdIUpMMK0MXmU85K/G3FMJ7CVmRATUXH5XbES2xm46W3eYiVExkDzRRb+QONI0sYd7ipCwKmoCmzBrGhY83K1fzWz/BAqwGvn7tQMZBIIoef8Q7xaM68tL45MFK5MMvqIAJqiVgIMt98IB2QegQSQHBpFnXfVaEdM37ZeBxDyG9NDSXLGYiXF5J5Af1IhC1ZCWn79sWi4p+hZMRp6qjCR32R3Q+/Jb6ktKVT3kTd4dLRU8+nCEA=="
      ]
    }
  }
}

=== opentdf/tests/tdf3-js/mocks/kas/rewrap/request-simple.json
{
  "entity": {
    "userId": "virtru26@gmail.com",
    "attributes": [
      {
        "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL2FhLnZpcnRydS5jb20vYXR0ci91bmlxdWUtaWRlbnRpZmllci92YWx1ZS83YjczODk2OC0xMzFhLTRkZTktYjRhMS1jOTIyZjYwNTgzZTMiLCJuYW1lIjoiN2I3Mzg5NjgtMTMxYS00ZGU5LWI0YTEtYzkyMmY2MDU4M2UzIiwiaWF0IjoxNTQwNTg2NTczLCJleHAiOjE1NDA2NzI5NzN9.7vhZCMgZF3ZY4mr7zHI17gQGGeC20BX1yGEwicL19DU"
      },
      {
        "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL2FhLnZpcnRydS5jb20vYXR0ci9wcmltYXJ5LW9yZ2FuaXphdGlvbi92YWx1ZS83YjczODk2OC0xMzFhLTRkZTktYjRhMS1jOTIyZjYwNTgzZTMiLCJuYW1lIjoiN2I3Mzg5NjgtMTMxYS00ZGU5LWI0YTEtYzkyMmY2MDU4M2UzIiwiaWF0IjoxNTQwNTg2NTczLCJleHAiOjE1NDA2NzI5NzN9.lq1Pfn4MR5DpjOlTXKMI8gioBOBNSBM9UT4SodLUXag"
      }
    ],
    "publicKey": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAseSTcIibaHJGyC+qIHht\nJ/vAFKhKzfv8KBbgeiH1/UVE+OrVWDASbuaEbE1RKZQsdax2UTAIQ7fC/uU6wzb2\nJbCLpXU8ckpBkxDtfSpm8jI/fRKlSyUetcnmp+bpKCHJ/9Zn3meqmRiAskyObQI2\nD5GTO3yiqr6edXn9Dz02l4tk6Px1yRMaPIPy2is41bRVGJHZVM3su7oWqA4oqxmh\nPE5qcqRj6lZ6PhXhD8fivump1par7XlJiNDl7+KcNxWimrQC0IXm7Xg9lFqLmDSF\nrkcJoVVz/v4C3nsNFPkick1w0Ov7FqCxLzQVNNR3KEOAe5dVzaJqtO2iw+RdCQ/Y\nKQIDAQAB\n-----END PUBLIC KEY-----\n",
    "cert": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ2aXJ0cnUyNkBnbWFpbC5jb20iLCJhdHRyaWJ1dGVzIjpbeyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWNtd2lPaUpvZEhSd2N6b3ZMMkZoTG5acGNuUnlkUzVqYjIwdllYUjBjaTkxYm1seGRXVXRhV1JsYm5ScFptbGxjaTkyWVd4MVpTODNZamN6T0RrMk9DMHhNekZoTFRSa1pUa3RZalJoTVMxak9USXlaall3TlRnelpUTWlMQ0p1WVcxbElqb2lOMkkzTXpnNU5qZ3RNVE14WVMwMFpHVTVMV0kwWVRFdFl6a3lNbVkyTURVNE0yVXpJaXdpYVdGMElqb3hOVFF3TlRnMk5UY3pMQ0psZUhBaU9qRTFOREEyTnpJNU56TjkuN3ZoWkNNZ1pGM1pZNG1yN3pISTE3Z1FHR2VDMjBCWDF5R0V3aWNMMTlEVSJ9LHsiand0IjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjbXdpT2lKb2RIUndjem92TDJGaExuWnBjblJ5ZFM1amIyMHZZWFIwY2k5d2NtbHRZWEo1TFc5eVoyRnVhWHBoZEdsdmJpOTJZV3gxWlM4M1lqY3pPRGsyT0MweE16RmhMVFJrWlRrdFlqUmhNUzFqT1RJeVpqWXdOVGd6WlRNaUxDSnVZVzFsSWpvaU4ySTNNemc1TmpndE1UTXhZUzAwWkdVNUxXSTBZVEV0WXpreU1tWTJNRFU0TTJVeklpd2lhV0YwSWpveE5UUXdOVGcyTlRjekxDSmxlSEFpT2pFMU5EQTJOekk1TnpOOS5scTFQZm40TVI1RHBqT2xUWEtNSThnaW9CT0JOU0JNOVVUNFNvZExVWGFnIn1dLCJwdWJsaWNLZXkiOiItLS0tLUJFR0lOIFBVQkxJQyBLRVktLS0tLVxuTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzZVNUY0lpYmFISkd5QytxSUhodFxuSi92QUZLaEt6ZnY4S0JiZ2VpSDEvVVZFK09yVldEQVNidWFFYkUxUktaUXNkYXgyVVRBSVE3ZkMvdVU2d3piMlxuSmJDTHBYVThja3BCa3hEdGZTcG04akkvZlJLbFN5VWV0Y25tcCticEtDSEovOVpuM21lcW1SaUFza3lPYlFJMlxuRDVHVE8zeWlxcjZlZFhuOUR6MDJsNHRrNlB4MXlSTWFQSVB5MmlzNDFiUlZHSkhaVk0zc3U3b1dxQTRvcXhtaFxuUEU1cWNxUmo2bFo2UGhYaEQ4Zml2dW1wMXBhcjdYbEppTkRsNytLY054V2ltclFDMElYbTdYZzlsRnFMbURTRlxucmtjSm9WVnovdjRDM25zTkZQa2ljazF3ME92N0ZxQ3hMelFWTk5SM0tFT0FlNWRWemFKcXRPMml3K1JkQ1EvWVxuS1FJREFRQUJcbi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLVxuIiwiaWF0IjoxNTQwNTg2NTczLCJleHAiOjE1NDA2NzI5NzN9.ccdWOGptT924_8efFu5HO7lGY7B5a_8VEiRuXdJwSCQ"
  },
  "policy": "eyJ1dWlkIjoiMTExMS0yMjIyLTMzMzMzLTQ0NDQ0LWFiZGRlZi10aW1lc3RhbXAiLCJib2R5Ijp7ImRhdGFBdHRyaWJ1dGVzIjpbeyJ1cmwiOiJodHRwczovL2FhLnZpcnRydS5jb20vYXR0ci91bmlxdWUtaWRlbnRpZmllci92YWx1ZS83YjczODk2OC0xMzFhLTRkZTktYjRhMS1jOTIyZjYwNTgzZTMiLCJuYW1lIjoiN2I3Mzg5NjgtMTMxYS00ZGU5LWI0YTEtYzkyMmY2MDU4M2UzIn0seyJ1cmwiOiJodHRwczovL2FhLnZpcnRydS5jb20vYXR0ci9wcmltYXJ5LW9yZ2FuaXphdGlvbi92YWx1ZS83YjczODk2OC0xMzFhLTRkZTktYjRhMS1jOTIyZjYwNTgzZTMiLCJuYW1lIjoiN2I3Mzg5NjgtMTMxYS00ZGU5LWI0YTEtYzkyMmY2MDU4M2UzIn1dLCJkaXNzZW0iOlsidmlydHJ1MjZAZ21haWwuY29tIl19fQ==",
  "binding": "MmZiYjYxYmQyNDJkMDFhZDJlOWJmY2JmMzM4MmEzMTgxYjY1ZjVmMmNjM2M3MWYzYTk0MTlmZDU3Njg3ZjYxNw==",
  "wrapped_key": "tzFpkQ3MHqb0O4N7AWJmzrZJKUNG+X5C+aWuQpGVGZe3sidnKb2TBcH75/ku26yeHa7VWax3syHwc2rgzr1cblTXXDDot/L8NX9iDGpG1GoucZO2KonxUB5ISfUnoGNKSouzHrfo/B8eyKAXlSCbi0BQzhScfGkEOT1YYr0Cs+BWQWN0pS4OXY73o0d0kWG0eVUl9jHK5dfc7BpeWKJANxu0ow1VR74XTnw2AL0Lk8opff59U58IxoUZDBuDLWGq1wUxhNlpzukYG6/Yje4XDN3jg82C9d/DPF/fnYWOxpXLx3wfScS3NqQCGpP+t6w21/rCDpXIsy5vwXdEQ6L/3A==",
  "auth_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NDA1ODY1NzMsImV4cCI6MTU0MDU4NjYzM30.BWhT4zEiEb60_PZyGXeYqZzaysuKPL2pCc-D4AHFEZiGzTSj0j9Mlsfj7qZiuEJhOKn_iufRztMzMJqCk0HboEatxwc4-XPxN5UOqw1zoyOy8J9A-V9JiT5aAvZ9E4nEg8TkEZeki1jlA9edyAuKD6dyv6_mt39ydB74KnKshwkh2uxmjzExa3hr_csVR9-QnHEYyM4nqJkU6-LpUBvgt0BhY0O6cz8R2ez-bKUnHQntYS5k-FaSpM1zMs-O-p9h0UZ6cl2PFgfqkwGC8aRLSQvljz_3GmxEp8_wqP02nFOBqt5Br5LclfStr8wKZjYvgu_kqT0D-6MdrmzccSzjEA",
  "metadata": {
    "algorithm": "AES-256-GCM",
    "iv": "DzF1r04BaAmf1Z4h",
    "ciphertext": "DzF1r04BaAmf1Z4hSTnKmWOVhfy29XKKadFj3g==",
    "plaintext": ""
  }
}
